# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: slides.accessibility.rocks
email: mail@yatil.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/waterslide/" # the subpath of your site, e.g. /blog
url: "https://slides.accessibility.rocks" # the base hostname & protocol for your site
twitter_username: yatil
github_username:  yatil
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

collections:
  2016_ahg_simplify:
    title: "Simplify your development life with tools, tests and procedures"
    date: "2016-11-15 13:30"
    conference: Accessing Higher Ground
    conference_url: "http://accessinghigherground.org/"
    output: true
    layout: slide
    permalink: /2016/ahg/simplify/:slug/
  2016_ahg_aaddd:
    title: "Advanced Accessibility: A Deep Dive for Developers"
    date: "2016-11-15 09:00"
    conference: Accessing Higher Ground
    conference_url: "http://accessinghigherground.org/"
    output: true
    layout: slide
    permalink: /2016/ahg/aaddd/:slug/
  2016_ahg_semantic:
    title: "Semantic Subtleties"
    date: "2016-11-17 08:00"
    conference: Accessing Higher Ground
    conference_url: "http://accessinghigherground.org/"
    output: true
    layout: slide
    permalink: /2016/ahg/semantic/:slug/
  2016_ahg_aria:
    title: "ARIA Serious?"
    date: "2016-11-17 16:00"
    conference: Accessing Higher Ground
    conference_url: "http://accessinghigherground.org/"
    output: true
    layout: slide
    permalink: /2016/ahg/aria/:slug/

defaults:
  - scope:
      path: ""
      type: 2016_ahg_simplify
    values:
      layout: slide
  - scope:
      path: ""
      type: 2016_ahg_aaddd
    values:
      layout: slide
  - scope:
      path: ""
      type: 2016_ahg_aria
    values:
      layout: slide
  - scope:
      path: ""
      type: 2016_ahg_semantic
    values:
      layout: slide
