# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: slides.accessibility.rocks
email: mail@yatil.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://slides.accessibility.rocks" # the base hostname & protocol for your site
twitter_username: yatil
github_username:  yatil
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

collections:
  2016_ahg_simplify:
    date: 2016-11-15
    time: 13:30
    conference: Accessing Higher Ground
    conference_url: "http://accessinghigherground.org/"
    output: true
    layout: slide
    permalink: /2016/ahg/simplify/:slug/
  2016_ahg_aaddd:
    date: 2016-11-15
    time: 13:30
    conference: Accessing Higher Ground
    conference_url: "http://accessinghigherground.org/"
    output: true
    layout: slide
    permalink: /2016/ahg/aaddd/:slug/

defaults:
  - scope:
      path: ""
      type: 2016_ahg_simplify
    values:
      layout: slide
  - scope:
      path: ""
      type: 2016_ahg_aaddd
    values:
      layout: slide